// <auto-generated />
using ApiAnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiAnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200403233436_UpdateSeedData")]
    partial class UpdateSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiAnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Comment");

                    b.Property<string>("Img");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 12,
                            Comment = "Eats Humans",
                            Img = "https://c402277.ssl.cf1.rackcdn.com/photos/18134/images/hero_small/Medium_WW226365.jpg?1574452099",
                            Name = "Jerry",
                            Type = "Tiger"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 10,
                            Comment = "Eats Humans",
                            Img = "https://upload.wikimedia.org/wikipedia/commons/e/e7/GarfieldStanding.jpg",
                            Name = "Lil T Bone",
                            Type = "Tiger"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 5,
                            Comment = "Reads English and French",
                            Img = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRFvER-gcaCz8GRzG5nFlSaJJ2xBJ_JM2uIoJq2JEgsziwwqPDt&usqp=CAU",
                            Name = "Jar Jar",
                            Type = "Tiger"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 12,
                            Comment = "Eats Everything",
                            Img = "https://outwardhound.com/buzzwoof/wp-content/uploads/2017/09/Old-Pug.jpg",
                            Name = "Dan",
                            Type = "Pug"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 11,
                            Comment = "Can not hear.",
                            Img = "https://i.ytimg.com/vi/J3lK7kZ0_mk/hqdefault.jpg",
                            Name = "Darth Varder",
                            Type = "Pug"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
