// <auto-generated />
using ApiAnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiAnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200403172624_AddSeeData")]
    partial class AddSeeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiAnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Comment");

                    b.Property<string>("Img");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 12,
                            Comment = "Eats Humans",
                            Img = "",
                            Name = "Jerry",
                            Type = "Tiger"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 12,
                            Comment = "Eats Humans",
                            Img = "",
                            Name = "Larry",
                            Type = "Tiger"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 12,
                            Comment = "Eats Humans",
                            Img = "",
                            Name = "Berry",
                            Type = "Tiger"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 12,
                            Comment = "Eats Humans",
                            Img = "",
                            Name = "Marry",
                            Type = "Tiger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
